BidARide/BidARide/Controllers/TripController.cs
using BidARide.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BidARide.Controllers
{
    public class TripController : Controller
    {
        const string API_Key = "AIzaSyBIAO62sl7gODaykvAl9VjDig8DLeqvThA";
        LocationInfo From, To;
        List<DriverInfomation> ListDriverNearLocation;
        //
        // GET: /Home/
        public ActionResult Index()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            Session.Remove("direction");
            Session.Remove("From");
            Session.Remove("To");
            return View();
        }

        public JsonResult GetNearDriver()
        {
            ListDriverNearLocation = getNearDiver();
            if (ListDriverNearLocation == null || ListDriverNearLocation.Count == 0)
            {
                ViewBag.Error = "No driver near your location.";
            }
            return new JsonResult { Data = ListDriverNearLocation, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetDirection()
        {
            LocationInfo from = new LocationInfo();
            from.address = Session["From"].ToString();
            LocationInfo to = new LocationInfo();
            to.address = Session["To"].ToString();

            DirectionInfo v = getDirection(from, to);
            Session["direction"] = v;
            return new JsonResult { Data = v, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private List<DriverInfomation> getAllDriver()
        {
            var request = WebRequest.Create("https://fast-hollows-58498.herokuapp.com/driver/coordInfo");
            request.ContentType = "application/json; charset=utf-8";
            string text;
            var response = (HttpWebResponse)request.GetResponse();

            using (var sr = new StreamReader(response.GetResponseStream()))
            {
                text = sr.ReadToEnd();

                JavaScriptSerializer js = new JavaScriptSerializer();

                JsonInfo jsoninfo = new JsonInfo(text);
                if (jsoninfo.status != 200)
                {
                    @ViewBag.Error = "Error " + jsoninfo.status;
                    return null;
                }

                if (jsoninfo.payload.Length == 0)
                {
                    @ViewBag.Error = "No driver near your location.";
                    return null;
                }

                // Cắt chuỗi để lấy thông tin JSon Payload
                string JsonPayload = text.Remove(0, 24);
                JsonPayload = JsonPayload.Remove(JsonPayload.Length - 1);

                dynamic dynObj = JsonConvert.DeserializeObject(JsonPayload);
                List<DriverInfomation> listDriver = new List<DriverInfomation>();
                foreach (var item in dynObj)
                {
                    string id = item.driverID;
                    string fullname = item.driverFullname;
                    string phone = item.driverPhone;
                    float lng = item.longitude;
                    float lat = item.latitude;
                    DriverInfomation driver = new DriverInfomation(id, fullname, phone, lng, lat);
                    listDriver.Add(driver);
                }

                return listDriver;
            }
        }

        private DirectionInfo getDirection(LocationInfo from, LocationInfo to)
        {
            DirectionInfo direction = new DirectionInfo();
            string origin = from.address, destination = to.address;
            if (origin == "" || origin == null)
            {
                origin = from.lat + "," + from.lng;
            }
            
            if (destination == "" || destination == null)
            {
                destination = to.lat + "," + to.lng;
            }

            var request = WebRequest.Create("https://maps.googleapis.com/maps/api/directions/json?origin=" + origin + "&destination=" + destination + "&key=" + API_Key);
            request.ContentType = "application/json; charset=utf-8";
            string text;
            var response = (HttpWebResponse)request.GetResponse();

            using (var sr = new StreamReader(response.GetResponseStream()))
            {
                text = sr.ReadToEnd();

                JavaScriptSerializer js = new JavaScriptSerializer();

                JsonDirectionInfo jsoninfo = new JsonDirectionInfo(text);
                if (jsoninfo.status != "OK")
                {
                    ViewBag.Error = "Error " + jsoninfo.status;
                    return null;
                }

                if (jsoninfo.routes.Length == 0)
                {
                    ViewBag.Error = "No direction.";
                    return null;
                }
                //string userID = Session["username"].ToString();
                dynamic d = JObject.Parse(text);
                var directions_legs = d.routes[0].legs;

                direction.distance_text = directions_legs[0].distance.text;
                direction.distance_value = directions_legs[0].distance.value;

                direction.start.address = directions_legs[0].start_address;
                direction.start.lat = directions_legs[0].start_location.lat;
                direction.start.lng = directions_legs[0].start_location.lng;

                direction.end.lat = directions_legs[0].end_location.lat;
                direction.end.lng = directions_legs[0].end_location.lng;
                direction.end.address = directions_legs[0].end_address;
            }
            return direction;
        }

        private List<DriverInfomation> getNearDiver()
        {
            LocationInfo from = new LocationInfo();
            from.address = Session["From"].ToString();
            ListDriverNearLocation = new List<DriverInfomation>();
            List<DriverInfomation> lstAllDriver = getAllDriver();
            foreach (DriverInfomation driver in lstAllDriver)
            {
                LocationInfo lc_diver = new LocationInfo();
                lc_diver.lat = driver.latitude;
                lc_diver.lng = driver.longtitude;
                DirectionInfo direc = getDirection(lc_diver, from);
                if (direc.distance_value <= 5000)
                {
                    ListDriverNearLocation.Add(driver);
                }
            }

            return ListDriverNearLocation;
        }

        public ActionResult findDriver (Trip model)
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ListDriverNearLocation = new List<DriverInfomation>();

            //From = getLocationFromAddress(model.tripFrom);
            //To = getLocationFromAddress(model.tripTo);
            LocationInfo from = new LocationInfo(), to = new LocationInfo();
            from.address = model.tripFrom; to.address = model.tripTo;
            Session["From"] = model.tripFrom;
            Session["To"] = model.tripTo;
            DirectionInfo direction = getDirection(from, to);

            
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> Booking(DriverInfomation driver)
        {
            HttpClient client = new HttpClient();
            string userID = Session["userID"].ToString();
            dynamic dir_session = Session["direction"];

            var values = new Dictionary<string, string>
            {
                { "userID", userID },
                { "driverID", driver.driverID },
                { "tripFrom", dir_session.start.address },
                { "tripTo", dir_session.end.address },
                { "fromLong", dir_session.start.lng.ToString()},
                { "fromLat", dir_session.start.lat.ToString() },
                { "toLong", dir_session.end.lng.ToString() },
                { "toLat", dir_session.end.lat.ToString() },

            };
            var content = new FormUrlEncodedContent(values);
            var response = await client.PostAsync("https://fast-hollows-58498.herokuapp.com/trip/create", content);
            var responseString = await response.Content.ReadAsStringAsync();

            string s = responseString.ToString();
            if (s != "OK")
            {
                ViewBag.Error = "Username or Email already exist";

            }
                //Session["username"] = model.account.Username;
            return new JsonResult { Data = "Sucessfull", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        //[HttpGet]
        //[AllowAnonymous]
        //private LocationInfo getLocationFromAddress(string address)
        //{
        //    LocationInfo location = new LocationInfo();
            
        //    var request = WebRequest.Create("https://maps.googleapis.com/maps/api/geocode/json?address=" + address + "&key=" + API_Key);
        //    request.ContentType = "application/json; charset=utf-8";
        //    string text;
        //    var response = (HttpWebResponse)request.GetResponse();

        //    using (var sr = new StreamReader(response.GetResponseStream()))
        //    {
        //        text = sr.ReadToEnd();

        //        JavaScriptSerializer js = new JavaScriptSerializer();

        //        JsonLocationInfo jsoninfo = new JsonLocationInfo(text);
        //        if (jsoninfo.status != "OK")
        //        {
        //            @ViewBag.Error = "Error " + jsoninfo.status;
        //            return null;
        //        }

BidARide/BidARide/Views/Shared/_LayoutHeader.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bid A Ride</title>
    <link href="~/Content/header-fixed.css" rel="stylesheet" />
    <link href="~/Content/header-user-dropdown.css" rel="stylesheet" />
</head>
<body>
    <header class="header-user-dropdown header-fixed">
        <div class="header-limiter">
            <a href="/#" >
                <h1>BID A RIDE</h1>
            </a>

            <div class="header-user-menu">
                <h5>@Session["username"]</h5>
                <ul>
                    <li><a href="#">Profile</a></li>
                    <li><a href="@Url.Action("Logout", "Account")">Logout</a></li>
                </ul>
            </div>
        </div>
    </header>
    <div>
        @RenderBody()
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>

        $(document).ready(function () {

            var showHeaderAt = 150;

            var win = $(window),
                    body = $('body');

            // Show the fixed header only on larger screen devices

            if (win.width() > 600) {

                // When we scroll more than 150px down, we set the
                // "fixed" class on the body element.

                win.on('scroll', function (e) {

                    if (win.scrollTop() > showHeaderAt) {
                        body.addClass('fixed');
                    }
                    else {
                        body.removeClass('fixed');
                    }
                });

            }

        });

    </script>
</body>
</html>

BidARide/BidARide/Views/Shared/_LayoutMap.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHeader.cshtml";

}
@model BidARide.Models.Trip
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        input[type=text], select {
            width: 250px;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=submit] {
            width: 150px;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

            input[type=submit]:hover {
                background-color: #45a049;
            }

        .angular-google-map-container {
            height: 300px;
            box-shadow: 2px 2px 3px 3px lightgrey;
        }

        .angular-google-map {
            width: 80%;
            height: 100%;
            margin: auto 0px;
        }
    </style>
    @* AngularJS library *@
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.6/angular.js"></script>
    @* google map*@
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js"></script>
    <script src="//rawgit.com/angular-ui/angular-google-maps/2.0.X/dist/angular-google-maps.js"></script>
    <script src="~/Scripts/ngMap.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/gmaps.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <style>
            /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
            #map {
                height: 700px;
                /*width: 100%;*/
            }
    </style>

    <script>
        //$("input[type='text']").keyup(function (e) {
        //    var s = document.getElementById("srclocation").value;
        //    alert(s);
        //});
    </script>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                @using (Html.BeginForm("findDriver", "Trip", FormMethod.Post))
                {
                    @Html.TextBoxFor(model => model.tripFrom, new { placeholder = Html.DisplayNameFor(m => m.tripFrom) })
                    @Html.TextBoxFor(model => model.tripTo, new { placeholder = Html.DisplayNameFor(m => m.tripTo) })
                    <input type="submit" value="TÌM TÀI XẾ" style="font-weight:bold;" ng-click="booking()">
                }
                @*<form name="frm" method="post">
                <input type="text" id="srclocation" name="srclocation" placeholder="From..." required>
                <input type="text" id="deslocation" name="deslocation" placeholder="To..." required>
                <input type="submit" value="ĐẶT XE" style="font-weight:bold;" ng-click="booking()">
            </form>*@
            </div>
        </div>
        
        <div class="row">
            <div id="dvMap" class="col-md-8">
                <div class="maps" id="map">
                </div>
            </div>
            <div class="col-md-4">
                @RenderBody()
            </div>
        </div>
    </div>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBIAO62sl7gODaykvAl9VjDig8DLeqvThA&callback=initMap">
    </script>
</body>
</html>